# A. G. Sangster

# This program downloads the 4 MAF files from TCGA using TCGAbiolinks 
# The 4 MAF files are generated by 4 different mutation calling pipelines



#------------------------------------------------------------------------------------------------ Set Preferences
# save the downloaded mutation annotation files (MAF) in their own directory
save_MAF_files = TRUE



#------------------------------------------------------------------------------------------------ Load Packages
library(TCGAbiolinks)



#------------------------------------------------------------------------------------------------ Download Data
# download MAF using TCGAbiolinks package
muse <- GDCquery_Maf("BLCA", pipelines = "muse")
mutect2 <- GDCquery_Maf("BLCA", pipelines = "mutect2")
somaticsniper <- GDCquery_Maf("BLCA", pipelines = "somaticsniper")
varscan2 <- GDCquery_Maf("BLCA", pipelines = "varscan2")

if (save_MAF_files){
  # make directory for MAF
  dir.create("TCGA-Data")
  thisDir <- getwd()
  setwd(paste(thisDir,"TCGA-Data",sep="/"))
  
  # save the MAF as csv
  write.csv(muse,"TCGA-BLCA-muse.csv",row.names = FALSE)
  write.csv(mutect2,"TCGA-BLCA-mutect2.csv",row.names = FALSE)
  write.csv(somaticsniper,"TCGA-BLCA-somaticsniper.csv",row.names = FALSE)
  write.csv(varscan2,"TCGA-BLCA-varscan2.csv",row.names = FALSE)
  
  # back to initial working directory
  setwd(thisDir)
}











